export const CREAR_USUARIO = 'CREAR_USUARIO';

export const MOSTRAR_ERROR = 'MOSTRAR_ERROR';

export const AGREGAR_TIRO = 'AGREGAR_TIRO';

export const AGREGAR_JUGADOR = 'AGREGAR_JUGADOR';

export const MOSTRAR_SPINNER = 'MOSTRAR_SPINNER';

export const ACTUALIZAR_NOMBRES = 'ACTUALIZAR_NOMBRES';