export const CREAR_USUARIO = "CREAR_USUARIO";
export const ERROR_ENTRADA_USUARIO = "ERROR_ENTRADA_USUARIO";
export const EXITO_ENTRADA_USUARIO = "EXITO_ENTRADA_USUARIO";

export const INICIAR_SESION = "INICIAR_SESION";
export const INICIO_SESION_EXITO = "INICIO_SESION_EXITO";
export const INICIO_SESION_ERROR = "INICIO_SESION_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
export const RECARGAR_PAGINA = "RECARGAR_PAGINA";
export const AGREGAR_TIRO = "AGREGAR_TIRO";
export const AGREGAR_JUGADOR = "AGREGAR_JUGADOR";
export const SELECCIONAR_JUGADOR = "SELECCIONAR_JUGADOR";
export const CANCELAR_SELECCIONAR_JUGADOR = "CANCELAR_SELECCIONAR_JUGADOR";
export const OBTENER_JUGADORES = "OBTENER_JUGADORES";
export const ELIMINAR_JUGADOR = "ELIMINAR_JUGADOR";
export const OBTENER_TIROS_USUARIO = "OBTENER_TIROS_USUARIO";
export const MOSTRAR_SPINNER = "MOSTRAR_SPINNER";
export const ACTUALIZAR_NOMBRES = "ACTUALIZAR_NOMBRES";
