export const CREAR_USUARIO = 'CREAR_USUARIO';
export const ERROR_ENTRADA_USUARIO = 'ERROR_ENTRADA_USUARIO';
export const EXITO_ENTRADA_USUARIO = 'EXITO_ENTRADA_USUARIO';

export const INICIAR_SESION = 'INICIAR_SESION'
export const INICIO_SESION_EXITO = 'INICIO_SESION_EXITO'
export const INICIO_SESION_ERROR = 'INICIO_SESION_ERROR'

export const AGREGAR_TIRO = 'AGREGAR_TIRO';

export const AGREGAR_JUGADOR = 'AGREGAR_JUGADOR';

export const MOSTRAR_SPINNER = 'MOSTRAR_SPINNER';

export const ACTUALIZAR_NOMBRES = 'ACTUALIZAR_NOMBRES';